server:
  port: 8083
spring:
  application:
    name: 'coffee-orders-consumer'
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: coffee-orders-listener-group
      auto-offset-reset: latest # only read the latest messages from the kafka topic, earliest - which is going to read all the messages from the beginning
    properties:
      schema.registry.url : http://localhost:8081